/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'customerName' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
  'customerEmail' : string,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export interface _SERVICE {
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];